### ISSUE TITLE
/variables and /variables-search harmonisation

### ISSUE THREAD

**Issue by marieALaporte** [plantbreeding/API#34] opened 2016-12-15 16:10 UTC
_From @cpommier on September 2, 2016 15:29_

The parameter /brapi/v1/variables?category={categoryName} allows to search all phenological or physiological traits accross several ontologies. It uses the trait.class filed of the returned json.

This seems redundant with /brapi/v1/variables-search?class=phenology
The solution might be to remove /variables?category and keep only /variables and /variables-search

Also we should document /variables-search and add an exemple of class (renamed as traitClasses forclarity) : 
"traitClasses" : ["phenology", "physiological trait"]

Bonus:
Missing pagination parameters on /variables and /variable-search

_Copied from original issue: plantbreeding/Documentation#31_

**Comment by marieALaporte** [comment] 2016-12-15 16:10
_From @gcornut on September 14, 2016 14:8_

@lukasmueller I can prepare a pull request if you want so everyone can better see the modifications this issue implies

**Comment by gcornut** [comment] 2016-12-16 11:03
Actually this issue is a duplicate of plantbreeding/API#11 and was fixed in pull request plantbreeding/API#12

**Closed by gcornut** 2016-12-16 11:03 UTC
Labels: enhancement
