### ISSUE TITLE
Need an ObservationVariablePUI

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/API#527] opened 2022-02-09 22:29 UTC
Currently we have observationVariableDbID:CO_356:1000037
But we don't have a way to store the URI of that ontology term: https://cropontology.org/rdf/CO_356:1000037
That would be much more W3C friendly, no?
Propose to add 
observationVariablePUI:https://cropontology.org/rdf/CO_356:1000037

possibly the same for TraitDbID, addition of a traitPUI ?

**Comment by BrapiCoordinatorSelby** [comment] 2022-02-12 00:01
Is this a duplicate of issue #510 ?

**Comment by BrapiCoordinatorSelby** [comment] 2022-02-16 21:54
Closing issue since it is a near duplicate of #510

**Closed as completed by BrapiCoordinatorSelby** 2022-02-16 21:54 UTC
